version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kraft
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  s3:
    image: localstack/localstack:latest
    environment:
      SERVICES: s3
      DATA_DIR: /tmp/localstack/data
    ports: ["4566:4566"]
