name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm i
      - name: Typecheck & Lint
        run: |
          pnpm -r run build --filter @kraft/web --dry-run || true
          pnpm -r run lint --filter @kraft/web || true
      - name: Build Web
        run: pnpm -r --filter @kraft/web build
